---
title: "Recreating a Chart from the Economist"
author: "Shafi Rubbani"
date: "4/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggplot2)
library(ggthemes)
library(janitor)
library(tidyverse)
```

```{r download_data, cache=TRUE}
download.file("http://infographics.economist.com/databank/Economist_eu-balance.csv",
              destfile = "Economist_eu-balance.csv",
              mode = "wb")

eu_balance <- read_csv("Economist_eu-balance.csv", skip = 1) 

eu_balance_account <- eu_balance %>% 
  gather(key = "year", value = "account_balance", `2009`:`2015`) %>% 
  mutate(year = as.numeric(year)) %>% 
  select(Country, year, account_balance)

eu_balance_budget <- eu_balance %>% 
  gather(key = "year", value = "budget_balance", `2009_1`:`2015_1`) %>% 
  select(Country, year, budget_balance) %>% 
  mutate(year = as.numeric(substring(year, 1, 4)))

eu_balance_all <- eu_balance_account %>% 
  full_join(eu_balance_budget) %>% 
  gather(key = "balance_type", value = "balance", account_balance, budget_balance) %>%   clean_names()
```

```{r balance_plot}
plot_prep <- eu_balance_all %>% 
  filter(country %in% c("Austria",
                        "Belgium",
                        "France",
                        "Germany",
                        "Greece",
                        "Ireland",
                        "Italy",
                        "Netherlands",
                        "Portugal",
                        "Spain")) %>%
  mutate(country = fct_collapse(country,
                                "Others" = c("Austria",
                                             "Belgium",
                                             "France",
                                             "Ireland",
                                             "Italy",
                                             "Portugal"),
                                group_other = FALSE)) %>%
  mutate(balance_type = fct_relevel(balance_type, "budget_balance", "account_balance")) %>% 
  mutate(balance_type = fct_collapse(balance_type,
                                     "Current-account Balance" = "account_balance",
                                     "Budget Balance" = "budget_balance")) %>% 
  mutate(balance = balance / 1000)

#eu_balance_plot <- 
plot_prep %>% 
  ggplot(aes(x = year, y = balance, fill = country)) +
  geom_col() +
  facet_wrap(~balance_type, scales = "free") +
  scale_y_continuous(position = "right") +
  labs(title = "Surfeit of surpluses",
       subtitle = "Euro-area €bn",
       caption = "Source: Eurostat",
       y = NULL) +
  theme_economist() +
  scale_fill_economist()
```


